
BEGIN;

ALTER TABLE run
  DROP COLUMN IF EXISTS id uuid,
  DROP COLUMN IF EXISTS team,
  DROP COLUMN IF EXISTS job_name;

ALTER TABLE test
  DROP COLUMN IF EXISTS run_id,
  DROP COLUMN IF EXISTS test;

DROP INDEX IF EXISTS id_idx;
DROP INDEX IF EXISTS team_job;
DROP INDEX IF EXISTS run_idx;

DROP EXTENSION IF EXISTS "uuid-ossp";

COMMIT;