BEGIN;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

ALTER TABLE run
  ADD COLUMN IF NOT EXISTS id uuid DEFAULT uuid_generate_v4(),
  ADD COLUMN IF NOT EXISTS team TEXT,
  ADD COLUMN IF NOT EXISTS job_name TEXT;

ALTER TABLE test
  ADD COLUMN IF NOT EXISTS run_id uuid DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS test TEXT;

CREATE INDEX IF NOT EXISTS id_idx ON run(id);
CREATE INDEX IF NOT EXISTS team_job ON run(team, job_name);
CREATE INDEX IF NOT EXISTS run_idx ON test(run_id);

COMMIT;