on:
  pull_request:
    branches:
      - master
name: build
jobs:
  go-test:
    name: Go Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: timescale/timescaledb-ha:pg14-latest
        env:
          POSTGRES_PASSWORD: testuser
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: checkout repo
        uses: actions/checkout@master

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.1
        id: go

      - name: install linters
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install golang.org/x/lint/golint@latest
          go install github.com/client9/misspell/cmd/misspell@latest

      - name: run linters
        run: |
          shopt -s globstar
          staticcheck ./...
          golint $(go list ./...)
          (GLOBIGNORE="vendor/*"; misspell -error **/*.go)

      - name: db migrations
        run: go run . migrate -p testuser -y disable

      - name: tests
        run: go test -v -tags integration ./...
