on:
  pull_request:
    branches:
    - master
name: build
jobs:
  go-test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: go1.19 linters
      uses: shoukoo/golang-pipeline/go1.19/linter@master
      with:
        ERRCHECK: off
    - name: go1.19 test
      uses: shoukoo/golang-pipeline/go1.19/test@master
